# Generated by Django 4.0.6 on 2022-08-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='timestampedmodel_ptr',
        ),
        migrations.DeleteModel(
            name='TimestampedModel',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
