# Generated by Django 4.0.6 on 2022-08-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa: E501
                ('timestamp', models.DateTimeField(auto_now_add=True)),  # noqa: E501
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя')),  # noqa: E501
            ],
        ),
    ]
