# Generated by Django 4.0.6 on 2022-08-15 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_remove_labels_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
