# Generated by Django 4.0.6 on 2022-08-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_alter_statuses_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuses',
            name='timestamp',
        ),
    ]
